baseURL = 'https://ispri-unsw.github.io/'
languageCode = 'en-us'
title = 'IsPri UNSW'
theme = 'research_group'
relativeURLs = true

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Team"
    url = "/team/"
    weight = 2
  [[menu.nav]]
    name = "Publications"
    url = "/publications/"
    weight = 3
  [[menu.nav]]
    name = "News"
    url = "/news/"
    weight = 4


[params]
  author = "IsPri UNSW"
  description = "Website for the Information Security and Privacy Research Group at UNSW"
  
  # Organization details
  organization_name = "IsPri UNSW"
  organization_full_name = "Information Security and Privacy Research Group at UNSW"
  
  # Copyright
  copyright_text = "Information Security and Privacy Research Group at UNSW"
  theme_url = 'https://github.com/mattrobball/hugo_research_group/'


[module]
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/js/bootstrap.bundle.min.js"

[caches]
  [caches.images]
    dir = ':cacheDir/images'